name: jitsi_meet_example
description: Demonstrates how to use the jitsi_meet plugin with the basic options.
version: 1.0.14
publish_to: 'none'


environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  omni_jitsi_meet:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
