name: omni_jitsi_meet_platform_interface
description: A common platform interface for the jitsi meet plugin valid for android, ios and web.
version: 1.0.14
homepage: https://github.com/thorito/jitsi_meet
repository: https://github.com/thorito/jitsi_meet/tree/master/omni_jitsi_meet_platform_interface

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

